services:
  HDA:
    image: tensorflow/tensorflow:latest-gpu-jupyter
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    volumes:
      - "hda_data:/data"
volumes:
  hda_data:
      